baseurl = "http://cf-learn.info"
languageCode = "en-us"
title = "Learning CFEngine 3"
builddrafts = false
theme = "hyde-x-zzamboni"
paginate = 10
canonifyurls = true
pluralizeListTitles = false
publishDir = "docs"
disqusShortname = "cf-learn"

[author]
    name = "Diego Zamboni"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/post/:title/"

[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # Used when a given page doesn't set its own.
#    Description = "Thoughts and musings."
#    defaultKeywords = "your,default,page,keywords"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
#    theme = "theme-base-0f"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "github"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
#    tagline = ""

    # Metadata used to drive integrations.
#    googleAuthorship = "Your Google+ profile ID"
#    googleAnalytics = "Your Google Analytics tracking code"
#    gravatarHash = "MD5 hash of your Gravatar email address"

    # Sidebar social links, avoid enabling too many of these if possible.
    # These should be full URLs.
    github = "http://github.com/zzamboni/cf-learn.info"
    linkedin = "http://mx.linkedin.com/in/zzamboni"
    googleplus = ""
    facebook = ""
    twitter = "http://twitter.com/LearningCF3"
